const CONST = {};

CONST.LANDING = "/";
CONST.PLANNING = "/planning";
CONST.RETRO = "/retro";
CONST.UNKNOWN = "*";

CONST.RETRO_STATUS_NONE = "NONE";
CONST.RETRO_STATUS_EDIT = "EDIT";
CONST.RETRO_STATUS_DELETE = "DELETE";

CONST.USER = "USER";
CONST.ADMIN = "ADMIN";

CONST.ROOM_ID = "room-id";
CONST.USER_ID = "user-id";

CONST.ADD = "ADD";
CONST.EDIT = "EDIT";

export default CONST;
